### ISSUE TITLE
2.0.1 breaks semver

### ISSUE THREAD

**Issue by hdabrows** [jonschlinkert/shallow-clone#2]
9f1afeb87b3b9e50ea4d91248a50b2e7aae7bafd changes the minimum Node version which is a breaking change that requires a major version bump. Could you please push a new patch release that reverts this?

I also think it's a very aggressive version constraint seeing as it excludes several still maintained LTS versions of Node.

**Comment by jonschlinkert** [comment]
https://travis-ci.org/jonschlinkert/shallow-clone/jobs/303372953

> Could you please push a new patch release that reverts this?

I wish I could publish a patch that gave me back the time I lost answering this issue. 

> I also think it's a very aggressive version constraint seeing as it excludes several still maintained LTS versions of Node.

I think it's a massive waste of everyone's time when people create issues without researching first.

**Comment by jonschlinkert** [comment]
> Could you please push a new patch release that reverts this?

I wish I could publish a patch that gave me back the time I lost answering this issue. 

> I also think it's a very aggressive version constraint seeing as it excludes several still maintained LTS versions of Node.

I think it's a massive waste of everyone's time when people create issues without researching first. 

> changes the minimum Node version which is a breaking change that requires a major version bump

Yes, because in 2.0.0 the code was updated to support `Map` and `Set`, which are only supported in the versions that are now correctly identified in `.travis.yml`. 

https://travis-ci.org/jonschlinkert/shallow-clone/jobs/303372953
