### ISSUE TITLE
NPM Validation Bypass advisory

### ISSUE THREAD

**Issue by deviansg** [jonschlinkert/shallow-clone#7]
Any chance the `kind-of` library dependency can be updated to 6.0.3 to fix this issue:
https://www.npmjs.com/advisories/1490

**Comment by doowb** [comment]
Updating to `kind-of@6.0.3` isn't necessary for this package since it specifies `^6.0.2` and npm will resolve to `6.0.3` because it falls within the semver range.

If you're having issues, check out [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) on steps you can take to ensure your package dependency tools install the latest patch.

When there are other changes to this package, we usually update the dependency version at that time. But until then, it's usually not necessary.
